search:
  paths:
    - "app/controllers"
    - "app/helpers"
    - "app/presenters"
    - "app/views"

ignore_unused:
  - activerecord.*
  - activemodel.*
  - date.*
  - helpers.submit.*
  - simple_form.*
  - time.*
  - titles.*
  - errors.messages.*
  - flashes.failure_after_create
  - flashes.failure_after_update
  - flashes.failure_when_forbidden
  - mailer.reminder.subject
  - mailer.email_confirmation.subject
  - mailer.reminder_confirmation.subject
  - mailer.reminder_error.subject
